name: Build wheels

on: [push, pull_request]

jobs:
  build_wheels_linux_x86_64:
    name: Build x86_64 wheels on ubuntu-22.04
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_ARCHS_LINUX: x86_64
          CIBW_REPAIR_WHEEL_COMMAND: ""

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./wheelhouse/*.whl

  build_wheels_linux_aarch64:
    name: Build aarch64 wheels on ubuntu-22.04
    # this is slow, only run when tagged for release or test
    if: startsWith(github.ref, 'refs/tags/v') || startsWith(github.ref, 'refs/tags/test')
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_ARCHS_LINUX: aarch64
          CIBW_REPAIR_WHEEL_COMMAND: ""

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./wheelhouse/*.whl

  build_wheels_macos_x86_64:
    name: Build x86_64 wheels on macos-12
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_ARCHS_MACOS: x86_64
          CIBW_REPAIR_WHEEL_COMMAND: ""

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./wheelhouse/*.whl

  build_wheels_macos_arm64:
    name: Build arm64 wheels on macos-12
    runs-on: macos-12

    steps:
      - uses: actions/checkout@v3

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.14.1
        env:
          CIBW_ARCHS_MACOS: arm64
          CIBW_TEST_SKIP: "*-macosx_arm64"
          CIBW_REPAIR_WHEEL_COMMAND: ""
          CIBW_BEFORE_BUILD: pip install --platform macosx_11_0 libcasm-global~=2.0.1

      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: ./wheelhouse/*.whl

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Set up requirements and configuration variables
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake
          pip install --upgrade pip wheel build

      - name: make
        shell: bash
        run: |
          python -m build

      - name: upload sdist
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/*.tar.gz

  upload_pypi:
    name: Publish [PyPI]
    needs: [build_wheels_linux_x86_64, build_wheels_linux_aarch64, build_wheels_macos_x86_64, build_wheels_macos_arm64, build_sdist]
    runs-on: ubuntu-latest
    # Specifying a GitHub environment is optional, but strongly encouraged
    # environment: release
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3.0.2
        with:
          name: dist
          path: dist

      - name: Check files
        run: ls -lR dist

      - name: Upload to PyPI
        # upload to PyPI on every tag starting with 'v'
        if: startsWith(github.ref, 'refs/tags/v')
        uses: pypa/gh-action-pypi-publish@v1.8.8

      - name: Publish package distributions to TestPyPI
        # upload to TestPyPi on every tag starting with 'test'
        if: startsWith(github.ref, 'refs/tags/test')
        uses: pypa/gh-action-pypi-publish@v1.8.8
        with:
          repository-url: https://test.pypi.org/legacy/
          skip-existing: true
