name: Testing source build on ubuntu-latest

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: checkout libcasm-xtal
        uses: actions/checkout@v3
        with:
          path: CASMcode_crystallography

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: checkout libcasm-global
        uses: actions/checkout@v3
        with:
          repository: prisms-center/CASMcode_global
          path: CASMcode_global

      - name: Set up requirements & configuration variables
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake
          pip install --upgrade pip wheel

      - name: make global
        shell: bash
        run: |
          cd CASMcode_global
          git submodule update --init --recursive
          pip install -v .

      - name: check global
        shell: bash
        run: |
          cd CASMcode_global
          pip freeze
          CASM_PREFIX=`python -m libcasm.casmglobal --prefix`
          echo "CASM_PREFIX: ${CASM_PREFIX}"
          if [ -d ${CASM_PREFIX}/.. ]; ls -hl ${CASM_PREFIX}/..; fi
          if [ -d ${CASM_PREFIX} ]; ls -hl ${CASM_PREFIX}; fi
          if [ -d ${CASM_PREFIX}/lib ]; ls -hl ${CASM_PREFIX}/lib; fi
          if [ -d ${CASM_PREFIX}/lib64 ]; ls -hl ${CASM_PREFIX}/lib64; fi
          if [ -d ${CASM_PREFIX}/include ]; ls -hl ${CASM_PREFIX}/include; fi

      - name: make test global
        shell: bash
        run: |
          cd CASMcode_global
          pip install -r test_requirements.txt
          python -m pytest -rsap python/tests

      - name: make
        shell: bash
        run: |
          cd CASMcode_crystallography
          pip install -v .

      - name: check
        shell: bash
        run: |
          cd CASMcode_crystallography
          pip freeze
          CASM_PREFIX=`python -m libcasm.casmglobal --prefix`
          echo "CASM_PREFIX: ${CASM_PREFIX}"
          ls -hl ${CASM_PREFIX}/..
          ls -hl ${CASM_PREFIX}
          ls -hl ${CASM_PREFIX}/lib
          ls -hl ${CASM_PREFIX}/lib64
          ls -hl ${CASM_PREFIX}/include
          ls -hl ${CASM_PREFIX}/xtal

      - name: make test
        shell: bash
        run: |
          cd CASMcode_crystallography
          pip install -r test_requirements.txt
          python -m pytest -rsap python/tests

      - name: Set up doc requirements
        run: |
          cd CASMcode_crystallography
          pip install -r doc_requirements.txt

      - name: build docs
        shell: bash
        run: |
          cd CASMcode_crystallography
          cd python/doc
          sphinx-build -b html . _build/html

      - name: upload docs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: libcasm-xtal-docs
          path: python/doc/_build/html
